language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

install:
  - composer clear-cache
  - composer install --no-interaction --prefer-dist

script: vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/php-coveralls -v

cache:
  directories:
    - $HOME/.composer/cache